from datetime import datetime
from app.models import ContractState

def generate_markdown_report(state: ContractState) -> str:
    """Generates a professional Markdown report from the audit state."""
    
    risk_score = state.get("risk_score", 0)
    risks = state.get("risks", [])
    clauses = state.get("clauses", [])
    
    # Determine risk level color/label
    if risk_score >= 70:
        score_label = "🔴 CRITICAL RISK"
    elif risk_score >= 40:
        score_label = "🟡 MEDIUM RISK"
    else:
        score_label = "🟢 LOW RISK"
        
    report = f"""# Contract Audit Report
*Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*

## 1. Executive Summary

**Overall Risk Score: {risk_score}/100 ({score_label})**

This report highlights potential legal risks found in the provided contract. Our multi-agent AI system has analyzed the clauses against standard risk playbooks.

---

## 2. Risk Breakdown

"""

    if not risks:
        report += "✅ No significant risks identified in the analyzed clauses.\n\n"
    else:
        for i, risk in enumerate(risks, 1):
            level_emoji = "🔴" if risk['risk_level'] == "High" else "🟡" if risk['risk_level'] == "Medium" else "🟢"
            
            report += f"### {i}. {risk['clause_type']} ({level_emoji} {risk['risk_level']} Risk)\n"
            report += f"**Issue:** {risk['issue']}\n\n"
            
            if risk.get('toxic_language'):
                report += f"> [!CAUTION]\n> **Toxic Language Identified:**\n> \"{risk['toxic_language']}\"\n\n"
                
            report += f"**Recommendation:** {risk['recommendation']}\n\n"
            
            if risk.get('suggested_alternative'):
                report += f"#### Proposed Alternative Clause:\n"
                report += f"```text\n{risk['suggested_alternative']}\n```\n\n"
            
            report += "---\n\n"

    report += "## 3. Analyzed Clauses\n"
    for clause in clauses:
        section_info = f" (Section: {clause['section']})" if clause.get('section') else ""
        report += f"### {clause['type']}{section_info}\n"
        report += f"```text\n{clause['text']}\n```\n\n"

    report += """---
*Note: This report is generated by an AI assistant for informational purposes and does not constitute legal advice. Please consult with a qualified legal professional before signing any agreement.*
"""
    return report
